name: air_quality
description: Air quality index from the World's Air Quality Index (WAQI) service.
version: 2.0.0
homepage: https://github.com/cph-cachet/flutter-plugins/tree/master/packages/air_quality

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
